"""rename actor_id→sender_id and add explicit notification relationships

Revision ID: 9430f4be875b
Revises: 99c3f35708c4
Create Date: 2025-11-21 15:13:48.893614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9430f4be875b'
down_revision: Union[str, Sequence[str], None] = '99c3f35708c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_notifications_actor_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.drop_constraint(op.f('notifications_actor_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'])
    op.drop_column('notifications', 'actor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_actor_id_fkey'), 'notifications', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_actor_id'), 'notifications', ['actor_id'], unique=False)
    op.drop_column('notifications', 'sender_id')
    # ### end Alembic commands ###
