"""init schema

Revision ID: 99c3f35708c4
Revises: 20241120_add_bio_media_asset
Create Date: 2025-11-21 14:06:21.331804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c3f35708c4'
down_revision: Union[str, Sequence[str], None] = '20241120_add_bio_media_asset'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_chats_owner_id'), 'group_chats', ['owner_id'], unique=False)
    op.create_table('group_chat_members',
    sa.Column('group_chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_chat_id', 'user_id')
    )
    op.add_column('messages', sa.Column('group_chat_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_messages_group_chat_id'), 'messages', ['group_chat_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'group_chats', ['group_chat_id'], ['id'], ondelete='CASCADE')
    op.add_column('posts', sa.Column('caption', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'posts', 'media_assets', ['media_asset_id'], ['id'], ondelete='SET NULL')
    op.drop_column('posts', 'content')
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'website')
    op.drop_column('users', 'location')
    op.add_column('posts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'caption')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_group_chat_id'), table_name='messages')
    op.drop_column('messages', 'group_chat_id')
    op.drop_table('group_chat_members')
    op.drop_index(op.f('ix_group_chats_owner_id'), table_name='group_chats')
    op.drop_table('group_chats')
    # ### end Alembic commands ###
